# Generated by Django 5.0.7 on 2024-11-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandhistory',
            name='time',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
