# Generated by Django 5.0.7 on 2025-02-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_commandhistory_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNS_Response',
            fields=[
                ('ip', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('dns_response_data', models.TextField()),
            ],
        ),
    ]
