# Generated by Django 5.0.7 on 2025-02-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0004_alter_commandhistory_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DNS_Response',
        ),
    ]
